# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              The Bio X Federation
description:        Thinking about it....
lang:               en

# Site base hostname & protocol, e.g. http://example.com
url: 'Bio-Training-Federation'

# Site subpath, e.g. /blog
baseurl:            "/website-2"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

logo: img/logo.png
logo2x: img/logo-2x.png
white_logo: img/logo-w.png
white_logo2x: img/logo-w2x.png


footer:
    copyright:     © 2022

# Social icons displayed in footer
social:
    facebook:       
    dribbble:
    instagram:      
    linkedin:       
    pinterest:      
    twitter:        
    vimeo:          
    youtube:

collections:
  docs:
    output: true

# Number of posts displayed on blog page
paginate:     7

# Blog path
paginate_path: "/blog/:num/"


# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:     #12345

# Google Analytics
google_analytics: #UA—XXXXXXXX-X

plugins:
  - jekyll-liquify
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

# Defaults
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
